package edu.ucab.ferreucab.view.dialogs;

import edu.ucab.ferreucab.controller.UbicacionDialogController;
import edu.ucab.ferreucab.model.Ubicacion;
import edu.ucab.ferreucab.utilities.Constantes;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

public class UbicacionDialog extends javax.swing.JDialog {

    private final UbicacionDialogController controller;
    private Integer indexSelected;
    private String[] dataUbicacion;

    /**
     * Creates new form UbicacionDialog
     */
    public UbicacionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new UbicacionDialogController();
        initGUI();
    }

    private void initGUI() {
        this.setTitle("Ubicaciones");
        this.setLocationRelativeTo(this);

        fillDataTable();
    }

    private String makeUbicacion() {
        StringBuilder sb = new StringBuilder();
        sb.append(dataUbicacion[0]);
        sb.append(dataUbicacion[1]);
        sb.append(dataUbicacion[2]);

        return sb.toString();
    }

    private String checkFields() {
        String message;
        if (pasilloTextField.getText().isEmpty()) {
            message = Constantes.CAMPO_VACIO;
        } else if (estanteTextField.getText().isEmpty()) {
            message = Constantes.CAMPO_VACIO;
        } else if (espacioTextField.getText().isEmpty()) {
            message = Constantes.CAMPO_VACIO;
        } else {
            message = Constantes.OK;
        }
        return message;
    }

    private void fillDataTable() {
        Optional<List<Ubicacion>> opUbicaciones = Optional.ofNullable(controller.getUbicaciones());

        String[] columnNames = {"Id", "Pasillo", "Estante", "Espacio"};
        TableModel tableModel;
        if (opUbicaciones.isPresent()) {
            List<Ubicacion> ubicaciones = opUbicaciones.get();
            Object[][] data = new Object[ubicaciones.size()][columnNames.length];

            int i = 0;
            for (Ubicacion ubi : ubicaciones) {
                data[i][0] = ubi.getId();
                data[i][1] = ubi.getPasillo();
                data[i][2] = ubi.getEstante();
                data[i][3] = ubi.getEspacio();
                i++;
            }
            tableModel = new DefaultTableModel(data, columnNames);

        } else {
            tableModel = new DefaultTableModel(columnNames, 0);
        }
        dataTable.setModel(tableModel);
        TableColumnModel tcm = dataTable.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
    }

    private void clearFields() {
        pasilloTextField.setText(null);
        estanteTextField.setText(null);
        espacioTextField.setText(null);

        messageLabel.setText(null);

        editButton.setEnabled(false);
        deleteButton.setEnabled(false);
        
        indexSelected = null;
    }

    private void fillFields() {
        pasilloTextField.setText(dataUbicacion[0]);
        estanteTextField.setText(dataUbicacion[1]);
        espacioTextField.setText(dataUbicacion[2]);
    }

    private void updateForm() {
        dataTable.clearSelection();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pasilloTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        estanteTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        espacioTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Pasillo:");

        jLabel2.setText("Estante:");

        jLabel3.setText("Espacio:");

        createButton.setBackground(new java.awt.Color(0, 204, 0));
        createButton.setText("Crear");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        cancelButton.setBackground(new java.awt.Color(204, 0, 0));
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(204, 204, 0));
        editButton.setText("Editar");
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        messageLabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pasilloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(espacioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createButton)
                                .addGap(31, 31, 31)
                                .addComponent(cancelButton)))
                        .addGap(18, 18, 18)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editButton)
                            .addComponent(deleteButton))))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        backPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {espacioTextField, estanteTextField, pasilloTextField});

        backPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, createButton});

        backPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, editButton});

        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pasilloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(estanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(espacioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(editButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(cancelButton))
                .addGap(18, 18, 18)
                .addComponent(messageLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String message = checkFields();
        if (message.equals(Constantes.OK)) {
            String pasillo = pasilloTextField.getText();
            String estante = estanteTextField.getText();
            String espacio = espacioTextField.getText();
            controller.createUbicacion(pasillo, estante, espacio);
            message = Constantes.UBICACION_CREADO;

            fillDataTable();
            clearFields();
        }
        messageLabel.setText(message);
    }//GEN-LAST:event_createButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String ubi = makeUbicacion();
        int answer = JOptionPane.showConfirmDialog(this,
                "¿Desea actualizar la ubicación " + ubi + "?",
                "Advertencia",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            String message = checkFields();
            if (message.equals(Constantes.OK)) {
                String pasillo = pasilloTextField.getText();
                String estante = estanteTextField.getText();
                String espacio = espacioTextField.getText();
                controller.updateUbicacion(indexSelected, pasillo, estante, espacio);
                fillDataTable();
            } else {
                messageLabel.setText(message);
            }
        }
        updateForm();
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String ubi = makeUbicacion();
        int answer = JOptionPane.showConfirmDialog(this,
                "¿Desea eliminar la ubicación " + ubi + "?",
                "Advertencia",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            controller.deleteUbicacion(indexSelected);
            fillDataTable();
        }
        updateForm();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        int rowSelected = dataTable.getSelectedRow();
        if (rowSelected >= 0) {
            indexSelected = Integer.parseInt(dataTable.getModel().getValueAt(rowSelected, 0).toString());
            dataUbicacion = controller.getUbicacionByIndex(indexSelected);

            fillFields();
            editButton.setEnabled(true);
            deleteButton.setEnabled(true);
        } else {
            updateForm();
        }
    }//GEN-LAST:event_dataTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField espacioTextField;
    private javax.swing.JTextField estanteTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField pasilloTextField;
    // End of variables declaration//GEN-END:variables
}
